#!/usr/bin/env python
import rospy
from keyboard.msg import Keyboard

class Listener(object):

    def __init__(self):
        self.sub = rospy.Subscriber('keyboard/binary', Keyboard, self.callback)

    def callback(self, msg):
        print "Key b: %d" % msg.K_b

if __name__=='__main__':
    rospy.init_node('test_keyboard_node')
    li = Listener()
    rospy.spin()

    
